"""
Generate a human-readable HTML proof page from a verity registry.
"""

from __future__ import annotations

from verity.models import Registry

_STATUS_COLOR = {
    "verified": "#22c55e",
    "open": "#94a3b8",
    "rejected": "#ef4444",
    "passing": "#22c55e",
    "pending": "#f59e0b",
    "failing": "#ef4444",
    "passed": "#22c55e",
    "collected": "#94a3b8",
    "stale": "#f59e0b",
    "failed": "#ef4444",
}


def _badge(status: str) -> str:
    color = _STATUS_COLOR.get(status, "#94a3b8")
    return (
        f'<span style="background:{color};color:#fff;padding:2px 8px;'
        f'border-radius:4px;font-size:0.8em;font-weight:600">{status}</span>'
    )


def _section(title: str, rows: list[str]) -> str:
    if not rows:
        return ""
    items = "\n".join(f"    <li>{r}</li>" for r in rows)
    return f"""
  <section>
    <h2>{title}</h2>
    <ul>
{items}
    </ul>
  </section>"""


def generate_html(registry: Registry) -> str:
    feat_map = {f.id: f.title for f in registry.features}
    claim_map = {c.id: c for c in registry.claims}
    test_map = {t.id: t for t in registry.tests}

    features = [
        f'<code>{f.id}</code> — {f.title}'
        for f in registry.features
    ]

    claims = [
        f'<code>{c.id}</code> — {c.title} {_badge(c.status)} '
        f'<small>(feature: <code>{c.feature_id}</code>)</small>'
        for c in registry.claims
    ]

    tests = []
    for t in registry.tests:
        claim_title = claim_map[t.claim_id].title if t.claim_id in claim_map else t.claim_id
        tests.append(
            f'<code>{t.id}</code> {_badge(t.status)} '
            f'<small>[{t.kind}] → claim: <code>{t.claim_id}</code> ({claim_title})</small>'
        )

    evidence = []
    for e in registry.evidence:
        test_obj = test_map.get(e.test_id)
        test_label = test_obj.id if test_obj else e.test_id
        evidence.append(
            f'<code>{e.id}</code> {_badge(e.status)} '
            f'<small>test: <code>{test_label}</code>'
            + (f' | artifact: <code>{e.artifact_path}</code>' if e.artifact_path else '')
            + '</small>'
        )

    releases = []
    for r in registry.releases:
        blob = (
            f' | blob: <code>{r.walrus_blob_id}</code>'
            if r.walrus_blob_id else ''
        )
        releases.append(
            f'<code>{r.id}</code> — v{r.version} '
            f'<small>{r.timestamp}{blob} | claims: {len(r.claim_ids)}</small>'
        )

    push_log = []
    for i, p in enumerate(registry.pushes, 1):
        push_log.append(
            f'{i}. [{p.backend}] {p.timestamp} — <code>{p.blob_id}</code>'
        )

    context = [
        f"<strong>{e.key}</strong>: {e.value}"
        for e in registry.context
    ]

    body = (
        _section("Project Context", context)
        + _section("Features", features)
        + _section("Claims", claims)
        + _section("Tests", tests)
        + _section("Evidence", evidence)
        + _section("Releases", releases)
        + _section("Push log", push_log)
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>verity proof page — {registry.repo_id}</title>
  <style>
    body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #1e293b; }}
    h1 {{ font-size: 1.6em; margin-bottom: 4px; }}
    .meta {{ color: #64748b; font-size: 0.9em; margin-bottom: 32px; }}
    h2 {{ font-size: 1.1em; color: #475569; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; margin-top: 28px; }}
    ul {{ list-style: none; padding: 0; }}
    li {{ padding: 6px 0; border-bottom: 1px solid #f1f5f9; font-size: 0.95em; }}
    code {{ background: #f1f5f9; padding: 1px 5px; border-radius: 3px; font-size: 0.9em; }}
    small {{ color: #64748b; }}
    footer {{ margin-top: 40px; color: #94a3b8; font-size: 0.85em; text-align: center; }}
  </style>
</head>
<body>
  <h1>verity proof page</h1>
  <p class="meta">
    repo: <code>{registry.repo_id}</code> &nbsp;|&nbsp;
    schema: <code>{registry.schema_version}</code>
  </p>
{body}
  <footer>Generated by <a href="https://pypi.org/project/walrus-verity/">walrus-verity</a></footer>
</body>
</html>
"""
